spring:
  config:
    import: optional:file:.env[.properties]
  r2dbc:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
management:
  endpoints:
    web:
      exposure:
        include: health, info
  endpoint:
    shutdown:
      enabled: true
springdoc:
  webjars:
    prefix: ""
  swagger-ui:
    operationsSorter: method
    tagsSorter: alpha
logging:
  level:
    org:
      springframework:
        cache: TRACE
  api:
    configs:
      cache: DEBUG
    services:
      cache: DEBUG
server:
  error:
    include-stacktrace: on_param
api:
  config:
    security:
      token:
        issuer: ${JWT_ISSUER}
        audience: ${JWT_AUDIENCE}
        secret: ${JWT_SECRET}
        access-token-expiration: ${JWT_ACCESS_TOKEN_EXPIRATION:30m}
        refresh-token-expiration: ${JWT_REFRESH_TOKEN_EXPIRATION:1d}